# config information

# server config information
server:
  mode: debug # debug,release
  host: 0.0.0.0
  port: 8090

# mongo config information
mongo:
  port: 27017

log:
  filePath: E:/Logging/go_sugared/