# config information

# server config information
server:
  mode: debug # debug,release
  host: 0.0.0.0
  port: 8090

# mongo config information
mongo:
  host: 106.14.205.94
  user: admin
  password: 123456
  port: 27017

log:
  filePath: E:/Logging/go_sugared/