info:
  contact: {}
paths:
  /hh/room/add:
    post:
      consumes:
      - application/json
      parameters:
      - description: 姓名
        in: query
        name: name
        required: true
        type: string
      - description: State
        in: query
        name: state
        type: integer
      - description: CreatedBy
        in: query
        name: created_by
        type: integer
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 新增房源信息
      tags:
      - 房源相关
  /hh/room/delete:
    post:
      consumes:
      - application/json
      parameters:
      - description: 房源id
        in: query
        name: id
        required: true
        type: string
      - description: State
        in: query
        name: state
        type: integer
      - description: CreatedBy
        in: query
        name: created_by
        type: integer
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 删除房源信息
      tags:
      - 房源相关
  /hh/room/getDetail:
    post:
      consumes:
      - application/json
      parameters:
      - description: 房源id
        in: query
        name: id
        required: true
        type: string
      - description: State
        in: query
        name: state
        type: integer
      - description: CreatedBy
        in: query
        name: created_by
        type: integer
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 获取某一个房源具体信息
      tags:
      - 房源相关
  /hh/room/update:
    post:
      consumes:
      - application/json
      parameters:
      - description: 房源id
        in: query
        name: id
        required: true
        type: string
      - description: State
        in: query
        name: state
        type: integer
      - description: CreatedBy
        in: query
        name: created_by
        type: integer
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 更新房源信息
      tags:
      - 房源相关
swagger: "2.0"
